config/routes.rb
Rails.application.routes.draw do

  resources :jobs

  get 'home/index'
  root 'home#index'
  get 'home/about'

end

app/models/job.rb
class Job < ActiveRecord::Base
	#belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def login
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		@jobs = Job.all
	end

	def show
    	@job = Job.find(params[:id])
  	end

  	def new
  		@job = Job.new
  	end

  	def create
  		@job = Job.new(job_params)

  		if @job.save
  			redirect_to @job
  		else
  			render 'new'
  		end
  	end

    def edit
      @job = Job.find(params[:id])
    end

    def update
      @job = Job.find(params[:id])

      if @job.update(job_params)
        redirect_to @job
      else
        render 'edit'
      end
    end

    def destroy
      @job = Job.find(params[:id])
      @job.destroy

      redirect_to jobs_path
    end

  	private
  	def job_params
  		params.require(:job).permit(:title, :description, :email, :city, :salary, :experience)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end

	def show
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/about.html.erb
<div class="hero-unit">
	<div class="row center-block">
		<div class="col-md-4 text-center">
			<i class="fa fa-plus-circle fa-5x" aria-hidden="true"></i>
			<h2>Reach</h2>
		</div> 
		<div class="col-md-4 text-center">
			<i class="fa fa-gg-circle fa-5x" aria-hidden="true"></i>
			<h2>Connection</h2>
		</div> 
		<div class="col-md-4 text-center">
			<i class="fa fa-laptop fa-5x" aria-hidden="true"></i>
			<h2>Solutions</h2>
		</div> 
	</div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">	
	<h1 style="text-align: center;">Job Finder</h1>
	<img class="center" src="http://macedoniabattlecreek.org/wp-content/uploads/2013/08/Job-Fair-1024x528.png" height="300">
	</br>
	<p style="text-align: center;">Welcome to the best site for job search!</p>
	<div class="col-md-12 text-center">
		<%= link_to 'Search jobs', jobs_path, class: "btn btn-primary btn-lg" %>
	</div>	
</div>

app/views/home/login.html.erb
<%= render 'partials/loginform' %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render 'partials/form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>All jobs</h1>

<table class="table table-hover" >
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th>Email</th>
		<th>City</th>
		<th>Salary</th>
		<th>Experience</th>
	</tr>

	<% @jobs.each do |job| %>
		<tr class=<%= job.experience ? "success" : "warning" %>>
			<td><%= job.title %></td>
			<td><%= job.description %></td>
			<td><%= job.email %></td>
			<td><%= job.city %></td>
			<td><%= job.salary %> KM</td>
			<td><%= job.experience ? "Yes" : "No" %></td>
			<td><%= link_to 'Show', job_path(job), :class=>"btn btn-default" %></td>
		</tr>
	<% end %>
</table>
</br>
<%= link_to 'New job',  new_job_path, :class=>"btn btn-primary" %>

app/views/jobs/new.html.erb
<%= form_for :job, url: jobs_path, :html => {:class => "form-horizontal center"} do |f| %>
	<% if @job.errors.any? %>
	 <div id="error_explanation">
	 	<h2>
	 		<%= pluralize(@job.erorrs.count, "error") %> prohibited this article from being saved:
	 	</h2>
	 	<ul>
	 		<% @job.erorrs.full_messages.each do |m| %>
	 			<li> <%= m %></li>
	 		<% end %>
	 	</ul>
	 </div>
	<% end %>

	<div class="form-group">
	 <%= f.label :title %></br>
	 <%= f.text_field :title %>
	</div>

	<div class="form-group">
		<%= f.label :description %></br>
		<%= f.text_area :description %>
	</div>

	<div class="form-group">
	 <%= f.label "Email address" %></br>
	 <%= f.text_field :email %>
	</div>

	<div class="form-group">
	 <%= f.label :city %></br>
	 <%= f.text_field :city %>
	</div>

	<div class="form-group">
	 <%= f.label :salary %></br>
	 <%= f.text_field :salary %>
	</div>

	<div class="form-group">
	 <%= f.label :experience %></br>
	 <%= f.check_box :experience, {}, true, false %> 
	</div>

	<div > <%= f.submit "Submit", class: "btn btn-default" %> </p>
<% end %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p>
	<strong>Description:</strong>
	<%= @job.description %>
</p>
<p>
	<strong>Email:</strong>
	<%= @job.email %>
</p>
<p>
	<strong>City:</strong>
	<%= @job.city %>
</p>
<p>
	<strong>Salary:</strong>
	<%= @job.salary %> KM
</p>
<p>
	<strong>Experience:</strong>
	<%= @job.experience ? "Yes" : "No" %>
</p>
<%= link_to 'Delete', job_path(@job), method: :delete, data: {confirm: 'Are you sure?' }, class:"btn btn-danger"%>
</br></br>
<%= link_to 'Edit', edit_job_path %>
</br></br>
<%= link_to 'Back to Jobs', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
	<%= render 'partials/navbar' %>
	       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

	<%= yield %>
</body>
</html>

app/views/partials/_form.html.erb
<%= form_for :job, url: jobs_path, :html => {:class => "form-horizontal center"} do |f| %>
	<% if @job.errors.any? %>
	 <div id="error_explanation">
	 	<h2>
	 		<%= pluralize(@job.erorrs.count, "error") %> prohibited this article from being saved:
	 	</h2>
	 	<ul>
	 		<% @job.erorrs.full_messages.each do |m| %>
	 			<li> <%= m %></li>
	 		<% end %>
	 	</ul>
	 </div>
	<% end %>

	<div class="form-group">
	 <%= f.label :title %></br>
	 <%= f.text_field :title %>
	</div>

	<div class="form-group">
		<%= f.label :description %></br>
		<%= f.text_area :description %>
	</div>

	<div class="form-group">
	 <%= f.label "Email address" %></br>
	 <%= f.text_field :email %>
	</div>

	<div class="form-group">
	 <%= f.label :city %></br>
	 <%= f.text_field :city %>
	</div>

	<div class="form-group">
	 <%= f.label :salary %></br>
	 <%= f.text_field :salary %>
	</div>

	<div class="form-group">
	 <%= f.label :experience %></br>
	 <%= f.check_box :experience, {}, true, false %> 
	</div>

	<div > <%= f.submit "Submit", class: "btn btn-default" %> </p>
<% end %>

app/views/partials/_loginform.html.erb
<h1>Login form</h1>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%= link_to 'JobFinder',  home_index_path %></a>
    </div>
   
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home',  home_index_path %></li>
        <li><%= link_to 'About',  home_about_path %></li>
        <li><%= link_to 'Jobs',  jobs_path %></li>
        <li><%= link_to 'Login', home_login_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>